alerting:
  discord:
    webhook-url: $GATUS_DISCORD_WEBHOOK
    default-alert:
      description: 'Health Check Failed for [ENDPOINT_NAME]'
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 5
