name: nas

services:
  beszel-agent:
    environment:
      KEY: ${BESZEL_KEY}
      LISTEN: 45876
    image: henrygd/beszel-agent:0.18.4
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  restic-server:
    image: restic/rest-server:0.14.0
    ports:
      - 8000:8000
    volumes:
      - /mnt/main/restic:/data
    restart: unless-stopped
