alerting:
  discord:
    webhook-url: '${GATUS_DISCORD_WEBHOOK}'
    default-alert:
      enable: true
      title: 'Monitoring Alert: {{ trigger.event.data.event_data.endpoint }}'
      send-on-resolved: true
      failure-threshold: 5
      success-threshold: 2
