endpoints:
  - name: homelab-home
    group: home
    url: 'icmp://100.101.55.71'
    interval: 1m
    conditions:
      - '[CONNECTED] == true'
    alerts:
      - type: discord

  - name: immich
    group: home
    url: 'http://immich.bwees.home'
    interval: 1m
    conditions:
      - '[STATUS] == 200'
    alerts:
      - type: discord

  - name: abkk-drive
    group: home
    url: 'icmp://100.125.237.53'
    interval: 1m
    conditions:
      - '[CONNECTED] == true'
    alerts:
      - type: discord

  - name: jellyfin
    group: home
    url: 'http://jellyfin.bwees.home'
    interval: 1m
    conditions:
      - '[STATUS] == 200'
    alerts:
      - type: discord

  - name: homeassistant
    group: home
    url: 'https://hass.bwees.io'
    interval: 1m
    conditions:
      - '[STATUS] == 200'
    alerts:
      - type: discord

  - name: photoframe
    group: home
    url: 'http://frame.bwees.home'
    interval: 1m
    conditions:
      - '[STATUS] == 200'
    alerts:
      - type: discord
