http:
  serversTransports:
    insecureTransport:
      insecureSkipVerify: true

  routers:
    orion:
      rule: 'Host(`orion.bwees.io`)'
      service: brandon-macbook-pro
      entryPoints:
        - public
        - publicsecure

    immich:
      rule: 'Host(`immich.bwees.io`)'
      service: homelab-bwees
      entryPoints:
        - public
        - publicsecure

    n8n:
      rule: 'Host(`n8n.bwees.io`)'
      service: homelab-bwees
      entryPoints:
        - public
        - publicsecure

    jellyfin:
      rule: 'Host(`jellyfin.bwees.io`)'
      service: homelab-bwees
      entryPoints:
        - public
        - publicsecure

    album:
      rule: 'Host(`album.bwees.io`)'
      service: homelab-home
      entryPoints:
        - public
        - publicsecure

    hass:
      rule: 'Host(`hass.bwees.io`)'
      service: homelab-home
      entryPoints:
        - public
        - publicsecure

    healthchecks:
      rule: 'Host(`hc.bwees.io`)'
      service: homelab-bwees
      entryPoints:
        - public
        - publicsecure

    stepien-immich:
      rule: 'Host(`stepien-immich.bwees.io`)'
      service: stepien-server
      entryPoints:
        - public
        - publicsecure

    starforge-cam:
      rule: 'Host(`cam.starforgefoundry.com`)'
      service: starforge-docker
      entryPoints:
        - public
        - publicsecure

    starforge-bambu-connect:
      rule: 'Host(`bambu-connect.starforgefoundry.com`)'
      service: starforge-docker
      entryPoints:
        - public
        - publicsecure

    starforge-hass:
      rule: 'Host(`hass.starforgefoundry.com`)'
      service: starforge-hass
      entryPoints:
        - public
        - publicsecure

  services:
    homelab-bwees:
      loadBalancer:
        servers:
          - url: 'https://100.65.90.4'
        serversTransport: insecureTransport

    homelab-home:
      loadBalancer:
        servers:
          - url: 'http://100.101.55.71'

    stepien-server:
      loadBalancer:
        servers:
          - url: 'http://100.81.233.29'

    starforge-docker:
      loadBalancer:
        servers:
          - url: 'https://100.125.29.116'
        serversTransport: insecureTransport

    starforge-hass:
      loadBalancer:
        servers:
          - url: 'http://10.0.10.173:8123' # Uses TS Subnet router

    brandon-macbook-pro:
      loadBalancer:
        servers:
          - url: 'http://100.89.139.58:5173' # Uses TS Subnet router
