name: maroonrides

networks:
  vps_traefik_backend:
    external: true
  vps_postgres:
    external: true

services:
  bugsink:
    image: bugsink/bugsink
    environment:
      - BASE_URL=https://bugsink.maroonrides.app
      - BEHIND_HTTPS_PROXY=True
      - SECRET_KEY=${BUGSINK_SECRET_KEY}
      - DATABASE_URL=postgresql://bugsink:${BUGSINK_PG_PASSWORD}@postgres:5432/bugsink
    networks:
      - vps_traefik_backend
      - vps_postgres
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.bugsink.loadbalancer.server.port=8000'
      - 'traefik.http.routers.bugsink.rule=Host(`bugsink.maroonrides.app`)'
      - 'traefik.http.routers.bugsink.service=bugsink'
      - 'traefik.http.routers.bugsink.entrypoints=publicsecure'
      - 'traefik.docker.network=vps_traefik_backend'
