- name: Deploy Docker Hosts
  hosts: all
  gather_facts: false
  roles:
    - role: bwees.deploy.deploy_host
      vars:
        deploy_dest: '{{ deployment_location | default("/home/" + ansible_ssh_user + "/deploy2-electric_boogaloo") }}'
        compose_src: '../compose/{{ deploy_source }}'
        config_src: '../configs/'
        secret_src: './secrets.resolved.yml'
        config_mode: 'multi_host'
        host_folder: '{{ deploy_source }}'
        secret_groups:
          - '{{ deploy_source }}'
          - 'shared'
