all:
  children:
    lab:
      hosts:
        homelab-bwees:
          ansible_ssh_user: bwees
      vars:
        deploy_source: lab

    home:
      hosts:
        homelab-home:
          ansible_ssh_user: bwees
      vars:
        deploy_source: home

    vps:
      hosts:
        homelab-vps:
          ansible_ssh_user: bwees
      vars:
        deploy_source: vps

    router:
      hosts:
        homelab-router:
          ansible_ssh_user: root

    nas:
      hosts:
        homelab-nas:
          ansible_ssh_user: root
          ansible_host: 192.168.50.4
      vars:
        deploy_source: nas
        deployment_location: /mnt/main/homelab/nas-deploy

    stepien:
      hosts:
        stepien-server:
          ansible_ssh_user: bwees
      vars:
        deploy_source: stepien
