endpoints:
  - name: immich
    group: stepien
    url: 'https://stepien-immich.bwees.io/'
    interval: 1m
    conditions:
      - '[STATUS] == 200'
    alerts:
      - type: discord

  - name: nas
    group: stepien
    url: 'icmp://100.102.56.35'
    interval: 1m
    conditions:
      - '[CONNECTED] == true'
    alerts:
      - type: discord

  # - name: stepien-server
  #   group: stepien
  #   url: 'icmp://100.81.233.29'
  #   interval: 1m
  #   conditions:
  #     - '[CONNECTED] == true'
  #   alerts:
  #     - type: discord
