providers:
  docker:
    exposedByDefault: false
    network: traefik_backend
  file:
    directory: /etc/traefik/config/dynamic
    watch: true

entryPoints:
  private:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: ':443'
          scheme: https
          permanent: true
          priority: 100000

  privatesecure:
    address: ':443'
    http:
      tls: {}

  public:
    address: ':81'
    http:
      redirections:
        entryPoint:
          to: ':443'
          scheme: https
          permanent: true
          priority: 100000

  publicsecure:
    address: ':444'
    http:
      tls: {}
